# Generated by Django 6.0.6 on 2026-06-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=250)),
                ('descripcion_1', models.TextField()),
                ('descripcion_2', models.TextField(blank=True)),
                ('imagen_equipo', models.ImageField(blank=True, upload_to='nosotros/')),
                ('pie_lista', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Página Nosotros',
            },
        ),
        migrations.CreateModel(
            name='PortadaCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('imagen', models.ImageField(upload_to='portadas/')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Portada',
                'verbose_name_plural': 'Portadas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('lista_servicios', models.TextField(blank=True, verbose_name='Nuestros Servicios')),
                ('por_que_elegirnos', models.TextField(blank=True, verbose_name='¿Por qué elegirnos?')),
                ('imagen', models.ImageField(upload_to='servicios/')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
