# Generated by Django 6.0.6 on 2026-06-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(max_length=120)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('descripcion_1', models.TextField()),
                ('descripcion_2', models.TextField(blank=True)),
                ('pie_lista', models.TextField(blank=True, help_text='Una línea por ítem')),
                ('imagen_equipo', models.ImageField(blank=True, null=True, upload_to='nosotros/')),
            ],
        ),
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('imagen', models.ImageField(upload_to='portadas/')),
            ],
        ),
        migrations.DeleteModel(
            name='PaginaNosotros',
        ),
        migrations.DeleteModel(
            name='PortadaCarrusel',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='lista_servicios',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='por_que_elegirnos',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
    ]
