# Generated by Django 6.0.6 on 2026-06-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_infonosotros_portada_delete_paginanosotros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='texto_columna_der',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='texto_columna_izq',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='titulo_columna_der',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servicio',
            name='titulo_columna_izq',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
