# Generated by Django 6.0.6 on 2026-06-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_servicio_texto_columna_der_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='orden',
            field=models.PositiveIntegerField(default=1, help_text='1 = primero, 2 = segundo...'),
        ),
    ]
